---
- name: nginx Install, Start and Server a static website
  hosts: prod
  become: yes
  tasks:

    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Website
      copy:
        src: index.html
        dest: /usr/share/nginx/html

    - name: Copy css file
      copy:      
        src: styles.css 
        dest: /usr/share/nginx/html

    - name: Copy java script file
      copy:
        src: scripts.js
        dest: /usr/share/nginx/html

    - name: Copy expresso images
      copy:
        scr: espresso.jpg
        dest: /usr/share/nginx/html    

    - name: Copy  cap images
      copy:
        scr: cappuccino.jpg
        dest: /usr/share/nginx/html

    - name: Copy latte images
      copy:
        scr: latte.jpg
        dest: /usr/share/nginx/html      
